### ISSUE TITLE
Nom des profils

### ISSUE THREAD

**Issue by valentin-dufois** [Web-Imac-2017/Groupe1#1]
Il faudrait définir les caractères autorisés dans les noms de profils, ainsi que la taille minimale et maximale de ces derniers.
Pour l'instant je pensais à cela:
- Alphabet majuscule, minuscule + chiffres + caractère accentués
- Pas d'emojis
- De 3 à 30 caractères
- Ponctuation limité à - . _

Vous en pensez quoi?

**Comment by JulienRst** [comment]
Ça me parait ok 👍 

A priori ce qui est plus simple c'est de stocker en lowercase les pseudos et de les afficher en uppercase first sauf si tu veux des pseudos style : theD4rkKn1ghT :)

**Comment by valentin-dufois** [comment]
Merci, et bonne idée pour l'UppercaseFirst :)
